// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmTLEo2PFIRoLIDTcx63I5czqO_6FXJeI',
    appId: '1:952191357393:web:3c2ba296c47053911d90f0',
    messagingSenderId: '952191357393',
    projectId: 'gastbook-app',
    authDomain: 'gastbook-app.firebaseapp.com',
    storageBucket: 'gastbook-app.firebasestorage.app',
    measurementId: 'G-SHCXL9YTPC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDc62APWCWUYqAE2JzWurGgOZOR1XLsk4U',
    appId: '1:952191357393:android:15f12442fd846ceb1d90f0',
    messagingSenderId: '952191357393',
    projectId: 'gastbook-app',
    storageBucket: 'gastbook-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUyQgWypFyp0NpjsGrfB5hxy6-aIDApLA',
    appId: '1:952191357393:ios:bc8015d460d822a21d90f0',
    messagingSenderId: '952191357393',
    projectId: 'gastbook-app',
    storageBucket: 'gastbook-app.firebasestorage.app',
    iosBundleId: 'com.example.gastbook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUyQgWypFyp0NpjsGrfB5hxy6-aIDApLA',
    appId: '1:952191357393:ios:bc8015d460d822a21d90f0',
    messagingSenderId: '952191357393',
    projectId: 'gastbook-app',
    storageBucket: 'gastbook-app.firebasestorage.app',
    iosBundleId: 'com.example.gastbook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmTLEo2PFIRoLIDTcx63I5czqO_6FXJeI',
    appId: '1:952191357393:web:f3a9059838acf7a51d90f0',
    messagingSenderId: '952191357393',
    projectId: 'gastbook-app',
    authDomain: 'gastbook-app.firebaseapp.com',
    storageBucket: 'gastbook-app.firebasestorage.app',
    measurementId: 'G-Y2V4TBKSNP',
  );
}
